//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.05 at 04:46:50 PM CET 
//


package dataObjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itinerary" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="flightNum" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="depTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="arrTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="flightDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="tickets" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fromCity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="toCity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itinerary"
})
@XmlRootElement(name = "flightData")
public class FlightData {

    protected List<FlightData.Itinerary> itinerary;

    /**
     * Gets the value of the itinerary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itinerary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItinerary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightData.Itinerary }
     * 
     * 
     */
    public List<FlightData.Itinerary> getItinerary() {
        if (itinerary == null) {
            itinerary = new ArrayList<FlightData.Itinerary>();
        }
        return this.itinerary;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="flightNum" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="depTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="arrTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="flightDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="tickets" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *       &lt;attribute name="fromCity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="toCity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flightNum",
        "depTime",
        "arrTime",
        "flightDate",
        "price",
        "tickets"
    })
    public static class Itinerary {

        @XmlElement(required = true)
        protected Integer flightNum;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar depTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar arrTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar flightDate;
        @XmlElement(required = true)
        protected Integer price;
        @XmlElement(required = true)
        protected Integer tickets;
        @XmlAttribute(name = "fromCity")
        protected String fromCity;
        @XmlAttribute(name = "toCity")
        protected String toCity;
        @XmlAttribute(name = "id")
        protected Integer id;

        /**
         * Gets the value of the flightNum property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFlightNum() {
            return flightNum;
        }

        /**
         * Sets the value of the flightNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFlightNum(Integer value) {
            this.flightNum = value;
        }

        /**
         * Gets the value of the depTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDepTime() {
            return depTime;
        }

        /**
         * Sets the value of the depTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDepTime(XMLGregorianCalendar value) {
            this.depTime = value;
        }

        /**
         * Gets the value of the arrTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getArrTime() {
            return arrTime;
        }

        /**
         * Sets the value of the arrTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setArrTime(XMLGregorianCalendar value) {
            this.arrTime = value;
        }

        /**
         * Gets the value of the flightDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFlightDate() {
            return flightDate;
        }

        /**
         * Sets the value of the flightDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFlightDate(XMLGregorianCalendar value) {
            this.flightDate = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPrice(Integer value) {
            this.price = value;
        }

        /**
         * Gets the value of the tickets property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTickets() {
            return tickets;
        }

        /**
         * Sets the value of the tickets property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTickets(Integer value) {
            this.tickets = value;
        }

        /**
         * Gets the value of the fromCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromCity() {
            return fromCity;
        }

        /**
         * Sets the value of the fromCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromCity(String value) {
            this.fromCity = value;
        }

        /**
         * Gets the value of the toCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToCity() {
            return toCity;
        }

        /**
         * Sets the value of the toCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToCity(String value) {
            this.toCity = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

    }

}
